Updated theme
engelsystem/engelsystem-doc pull request #7
Opened 2024-04-08 19:48 UTC by MyIgel

The current theme is no longer supported, this seems to be the successor.

2024-04-10 20:13 UTC, xuwhite requested changes
So Long, and Thanks for All the Fish

2024-04-10 20:13 UTC, xuwhite commented on content/admin/configuration.md
>      // Available themes
some available themes pls

2024-04-10 20:13 UTC, xuwhite commented on content/admin/configuration.md
> +    // 'goodie' => a goodie which has no sizing options
fix pls

2024-04-10 20:13 UTC, xuwhite commented on content/admin/configuration.md
> +    // Resembles the Goodie Type. There are three options:
fix goody pls

2024-04-10 20:13 UTC, xuwhite commented on content/admin/configuration.md
> +    'goodie_type'      => 'tshirt',
fix goody pls

2024-04-10 20:13 UTC, xuwhite commented on content/api/_index.md
> +It might change at any time without further notice but should be "stable" during an event.
what event? when?

2024-04-10 20:13 UTC, xuwhite commented on content/api/_index.md
> +The API is accessible to Bureaucrats or users in the `API` group to allow for testing but to not confuse regular users.
```suggestion
The API is accessible to users in the `API` or ` Bureaucrat` group to allow for testing but to not confuse regular users.
```

2024-04-10 20:13 UTC, xuwhite commented on content/developer/_index.md
> +This documentation provides some additional background on extending and hacking around the Engelsystem.
does not work for me

2024-04-10 20:13 UTC, xuwhite commented on content/developer/_index.md
> +New Versions are normally released after bigger events like the Chaos Communication Congress and thus
events?

2024-04-10 20:13 UTC, xuwhite commented on content/developer/_index.md
> +External dependencies should do their function well and be actively maintained.
```suggestion
External dependencies should fulfill their function well and be actively maintained.
```

2024-04-10 20:13 UTC, xuwhite commented on content/developer/request-lifecycle.md
> +Our goal with this overview is to give you a basic understanding how the Engelsystem handles a request
```suggestion
The goal of this overview is to give you a basic understanding of how the Engelsystem handles a request
and provide a way to troubleshoot problems if they occur.
```

2024-05-05 17:11 UTC, MyIgel commented on content/developer/_index.md
> +This documentation provides some additional background on extending and hacking around the Engelsystem.
Then feel free to improve it ;)

2024-08-08 20:28 UTC, xuwhite approved these changes
looks good to me

2024-08-08 21:41 UTC, merged